-- MySQL Script generated by MySQL Workbench
-- Thu Sep 13 19:42:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs467_employee_recognition
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cs467_employee_recognition` ;

-- -----------------------------------------------------
-- Schema cs467_employee_recognition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs467_employee_recognition` DEFAULT CHARACTER SET utf8 ;
USE `cs467_employee_recognition` ;

-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role`;
CREATE TABLE IF NOT EXISTS `role` (  
	`role_id` 	INT NOT NULL AUTO_INCREMENT,
  	`role` 		VARCHAR(50) NOT NULL,	
  	
  	PRIMARY KEY 	(`role_id`),
  	UNIQUE INDEX 	`role_UNIQUE` (`role`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_profile` ;
CREATE TABLE IF NOT EXISTS `user_profile` (  
  	`user_profile_id` 	INT NOT NULL AUTO_INCREMENT,
  	`first_name` 		VARCHAR(50) NOT NULL,
  	`last_name` 		VARCHAR(50) NOT NULL,
  	`signature_file` 	VARCHAR(255) NOT NULL,
  	
  	PRIMARY KEY (`user_profile_id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;
CREATE TABLE IF NOT EXISTS `user` (
  	`user_id` 			INT NOT NULL AUTO_INCREMENT,  	
  	`email` 			VARCHAR(255) NOT NULL,
  	`password` 			VARCHAR(255) NOT NULL,
  	`time_created` 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `role_id` 	INT NULL,
  	`user_profile_id` 	INT NULL,

	PRIMARY KEY (`user_id`),
  	UNIQUE INDEX `email_UNIQUE` (`email`),  
	
    INDEX `fk_user_user_profile_id1_idx` (`user_profile_id` ASC),
    INDEX `fk_user_role_id1_idx` (`role_id` ASC),
    
	CONSTRAINT `fk_user_role_id1`
		FOREIGN KEY (`role_id`)	REFERENCES `role`(`role_id`)
			ON DELETE NO ACTION
			ON UPDATE NO ACTION,
            
    CONSTRAINT `fk_user_user_profile_id1`
		FOREIGN KEY (`user_profile_id`)	REFERENCES `user_profile`(`user_profile_id`)
			ON DELETE CASCADE
			ON UPDATE CASCADE   
	     	
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `position` ;
CREATE TABLE IF NOT EXISTS `position` (
  	`position_id` 	INT NOT NULL AUTO_INCREMENT,
  	`position` 		VARCHAR(50) NOT NULL,
  
  	PRIMARY KEY (`position_id`),
  	UNIQUE INDEX `position_UNIQUE` (`position`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

CREATE TABLE IF NOT EXISTS `department` (
  	`department_id` 	INT NOT NULL AUTO_INCREMENT,
  	`department` 		VARCHAR(50) NOT NULL,
  	
  	PRIMARY KEY (`department_id`),
  	UNIQUE INDEX `department_UNIQUE` (`department`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `state` ;
CREATE TABLE IF NOT EXISTS `state` (
  	`state_id` INT NOT NULL AUTO_INCREMENT,
  	`state` VARCHAR(50) NOT NULL,
  	
  	PRIMARY KEY (`state_id`),
  	UNIQUE INDEX `state_UNIQUE` (`state`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;
CREATE TABLE IF NOT EXISTS `employee` (
  	`employee_id` 	INT NOT NULL AUTO_INCREMENT,
  	`first_name` 	VARCHAR(50) NOT NULL,
  	`last_name` 	VARCHAR(50) NOT NULL,
  	`email` 		VARCHAR(255) NOT NULL,
  	`gender` 		VARCHAR(6) NOT NULL,
  	`birth_date` 	DATE NOT NULL,
  	`state_id` 		INT NOT NULL,
  	`position_id` 	INT NOT NULL,
  	`department_id` INT NOT NULL,
  	
  	PRIMARY KEY (`employee_id`),
  	INDEX `fk_employee_position1_idx` (`position_id` ASC),
  	INDEX `fk_employee_department1_idx` (`department_id` ASC),
  	INDEX `fk_employee_state1_idx` (`state_id` ASC),
  
  	CONSTRAINT `fk_employee_position1`
    	FOREIGN KEY (`position_id`)	REFERENCES `position` (`position_id`)
    		ON DELETE NO ACTION
    		ON UPDATE NO ACTION,
  	CONSTRAINT `fk_employee_department1`
    	FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`)
    		ON DELETE NO ACTION
    		ON UPDATE NO ACTION,
  	CONSTRAINT `fk_employee_state1`
	    FOREIGN KEY (`state_id`) REFERENCES `state` (`state_id`)
    		ON DELETE NO ACTION
    		ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`award_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `award_type` ;
CREATE TABLE IF NOT EXISTS `award_type` (
  	`award_type_id` 	INT NOT NULL AUTO_INCREMENT,
  	`type` VARCHAR(255) NOT NULL,
  	
  	PRIMARY KEY (`award_type_id`),
  	UNIQUE INDEX `type_UNIQUE` (`type`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs467_employee_recognition`.`award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `award` ;
CREATE TABLE IF NOT EXISTS `award` (
  	`award_id` 		INT NOT NULL AUTO_INCREMENT,
  	`user_id` 		INT NOT NULL,
  	`employee_id` 	INT NOT NULL,
  	`award_type_id` INT NOT NULL,
  	`date_time` 	DATETIME NOT NULL,
  
  	PRIMARY KEY (`award_id`),
  	INDEX `fk_award_user1_idx` (`user_id` ASC),
  	INDEX `fk_award_employee1_idx` (`employee_id` ASC),
  	INDEX `fk_award_award_type1_idx` (`award_type_id` ASC),
  	CONSTRAINT `fk_award_user1`
    	FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`)
    		ON DELETE NO ACTION
    		ON UPDATE NO ACTION,
  	CONSTRAINT `fk_award_employee1`
    	FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`)
    		ON DELETE NO ACTION
    		ON UPDATE NO ACTION,
  	CONSTRAINT `fk_award_award_type1`
    	FOREIGN KEY (`award_type_id`) REFERENCES `award_type` (`award_type_id`)
    		ON DELETE NO ACTION
    		ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
